export const institutions = {
  "10th": ["School A", "School B", "School C", "School D"],
  "12th": ["School E", "School F", "School G", "School H"],
  UG: [
    "IIT Bombay",
    "IIT Delhi",
    "IIT Kanpur",
    "IIT Kharagpur",
    "IIT Madras",
    "IIT Roorkee",
    "IIT Guwahati",
    "IIT Hyderabad",
    "IIT BHU",
    "NIT Trichy",
    "NIT Surathkal",
    "NIT Warangal",
    "NIT Calicut",
    "VIT Vellore",
    "BITS Pilani",
    "CU Chandigarh",
    "MIT Pune",
    "Amity University",
  ],
  PG: [
    "IIT Bombay",
    "IIT Delhi",
    "IIT Kanpur",
    "IIT Kharagpur",
    "IIT Madras",
    "IIT Roorkee",
    "NIT Trichy",
    "BITS Pilani",
    "CU Chandigarh",
    "MIT Pune",
  ],
  PhD: ["IIT Bombay", "IIT Delhi", "IIT Kanpur", "BITS Pilani", "MIT Pune"],
};
